# Generated by Django 4.2.3 on 2023-07-19 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dronetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('typename', models.CharField(max_length=200)),
                ('weight', models.PositiveBigIntegerField()),
                ('maxspeed', models.PositiveIntegerField()),
                ('battery_capacity', models.PositiveBigIntegerField()),
                ('control_range', models.PositiveBigIntegerField()),
                ('maxcarriage', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(max_length=200)),
                ('carriage_weight', models.PositiveBigIntegerField()),
                ('carriage_type', models.CharField(max_length=200)),
                ('speed', models.PositiveBigIntegerField()),
                ('alignment', models.PositiveIntegerField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('battery_status', models.PositiveBigIntegerField()),
                ('last_seen', models.DateTimeField()),
                ('status', models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline'), ('IS', 'Issues')], default='OF', max_length=2)),
                ('dronetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.dronetype')),
            ],
        ),
    ]
