# Generated by Django 4.2.3 on 2023-07-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='alignment',
        ),
        migrations.AddField(
            model_name='drone',
            name='align_pitch',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='drone',
            name='align_roll',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='drone',
            name='align_yaw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='drone',
            name='carriage_type',
            field=models.CharField(choices=[('SEN', 'Sensors'), ('ACT', 'Actuators'), ('NOT', 'Nothing')], default='NOT', max_length=3),
        ),
        migrations.AlterField(
            model_name='drone',
            name='carriage_weight',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drone',
            name='serialnumber',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
