# Generated by Django 4.2.3 on 2023-07-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_remove_drone_alignment_drone_align_pitch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='serialnumber',
            field=models.CharField(help_text='Must be a unique text within all drones', max_length=200, unique=True),
        ),
    ]
