# Generated by Django 4.2.3 on 2023-07-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_alter_drone_serialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='align_pitch',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current algnment on y-axis', max_digits=3),
        ),
        migrations.AlterField(
            model_name='drone',
            name='align_roll',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current alignment on x-axis', max_digits=3),
        ),
        migrations.AlterField(
            model_name='drone',
            name='align_yaw',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current alignment on z-axis', max_digits=3),
        ),
        migrations.AlterField(
            model_name='drone',
            name='battery_status',
            field=models.PositiveBigIntegerField(help_text='Current battery charge in mAh'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='carriage_weight',
            field=models.PositiveBigIntegerField(default=0, help_text='Current additional carriage in g'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='last_seen',
            field=models.DateTimeField(help_text='Last contact to drone'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Current position latitude with a precision of 6 decimal places', max_digits=9),
        ),
        migrations.AlterField(
            model_name='drone',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='Current position longitude with a precision of 6 decimal places', max_digits=9),
        ),
        migrations.AlterField(
            model_name='drone',
            name='speed',
            field=models.PositiveBigIntegerField(help_text='Current speed in km/h'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='battery_capacity',
            field=models.PositiveBigIntegerField(help_text='Battery capacity in mAh'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='control_range',
            field=models.PositiveBigIntegerField(help_text='Control range in m'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='maxcarriage',
            field=models.PositiveBigIntegerField(help_text='Maximum carriage in g'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='maxspeed',
            field=models.PositiveIntegerField(help_text='Maximum speed in km/h'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='weight',
            field=models.PositiveBigIntegerField(help_text='Weight in g'),
        ),
    ]
