# Generated by Django 4.2.3 on 2023-07-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_alter_drone_align_pitch_alter_drone_align_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='align_pitch',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current algnment on y-axis', max_digits=5),
        ),
        migrations.AlterField(
            model_name='drone',
            name='align_roll',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current alignment on x-axis', max_digits=5),
        ),
        migrations.AlterField(
            model_name='drone',
            name='align_yaw',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current alignment on z-axis', max_digits=5),
        ),
    ]
