# Generated by Django 4.2.3 on 2023-07-24 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_alter_drone_align_pitch_alter_drone_align_roll_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dronetype',
            old_name='maxspeed',
            new_name='max_speed',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='align_pitch',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='align_roll',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='align_yaw',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='battery_status',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='maxcarriage',
        ),
        migrations.AddField(
            model_name='drone',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 24, 9, 15, 19, 705086, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dronetype',
            name='max_carriage',
            field=models.PositiveIntegerField(default=0, help_text='Maximum carriage in g'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='carriage_weight',
            field=models.PositiveIntegerField(default=0, help_text='Current additional carriage in g'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='battery_capacity',
            field=models.PositiveIntegerField(help_text='Battery capacity in mAh'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='control_range',
            field=models.PositiveIntegerField(help_text='Control range in m'),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='typename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dronetype',
            name='weight',
            field=models.PositiveIntegerField(help_text='Weight in g'),
        ),
        migrations.CreateModel(
            name='DroneDynamics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('speed', models.PositiveIntegerField(help_text='Current speed in km/h')),
                ('align_roll', models.DecimalField(decimal_places=2, default=0.0, help_text='Current alignment on x-axis', max_digits=5)),
                ('align_pitch', models.DecimalField(decimal_places=2, default=0.0, help_text='Current algnment on y-axis', max_digits=5)),
                ('align_yaw', models.DecimalField(decimal_places=2, default=0.0, help_text='Current alignment on z-axis', max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Current position longitude with a precision of 6 decimal places', max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Current position latitude with a precision of 6 decimal places', max_digits=9)),
                ('battery_status', models.PositiveIntegerField(help_text='Current battery charge in mAh')),
                ('last_seen', models.DateTimeField(help_text='Last contact to drone')),
                ('status', models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline'), ('IS', 'Issues')], default='OF', max_length=2)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.drone')),
            ],
        ),
    ]
