# Generated by Django 4.2.3 on 2023-07-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_rename_maxspeed_dronetype_max_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronedynamics',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamics', to='simulator.drone'),
        ),
    ]
