# Generated by Django 4.2.3 on 2023-07-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_alter_dronedynamics_drone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronedynamics',
            name='latitude',
            field=models.DecimalField(decimal_places=9, help_text='Current position latitude with a precision of 6 decimal places', max_digits=12),
        ),
        migrations.AlterField(
            model_name='dronedynamics',
            name='longitude',
            field=models.DecimalField(decimal_places=9, help_text='Current position longitude with a precision of 6 decimal places', max_digits=12),
        ),
    ]
