# Generated by Django 4.2.7 on 2023-11-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0010_alter_drone_carriage_type_alter_dronedynamics_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('static', 'Static'), ('live', 'Live')], max_length=10)),
            ],
        ),
    ]
