# Generated by Django 5.2.17 on 2026-10-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_simulatorsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimulatorSettings',
        ),
        migrations.AddIndex(
            model_name='dronedynamics',
            index=models.Index(fields=['timestamp', 'id'], name='simulator_d_timesta_797d2a_idx'),
        ),
    ]
