# syntax=docker/dockerfile:1
version: '3.8'

services:
  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A dronesim worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./env.dev
    depends_on:
      - web
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env.dev
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver --insecure 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "80:8000"
    env_file:
      - ./env.dev
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
    redis_data:
