# syntax=docker/dockerfile:1
version: '3.8'

services:

  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A dronesim worker
    volumes:
      - .:/app
    env_file:
      - ./env.prod
    depends_on:
      - web
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env.prod
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn dronesim.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./env.prod
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  redis_data:
