# syntax=docker/dockerfile:1
version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver --insecure 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "80:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:
