services:

  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A dronesim worker
    volumes:
      - .:/app
    env_file:
      - ./env.prod
    depends_on:
      - web
      - db
      - redis

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  db:
    image: postgres:18
    volumes:
      - pg_data:/var/lib/postgresql
    env_file:
      - ./env.prod
#    environment:
#      POSTGRES_DB: dronesim
#      POSTGRES_USER: dronesim
#      POSTGRES_PASSWORD: 23kjhrb32ouriz2gr3p2zrgro2zu3brhv1209

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn dronesim.wsgi:application --bind 0.0.0.0:8098
    ports:
      - "127.0.0.1:8098:8098"
    volumes:
      - static_volume:/app/staticfiles
      - dronesim_logs:/var/log/dronesim
    env_file:
      - ./env.prod
    depends_on:
      - db
      - redis

volumes:
  pg_data:
  static_volume:
  redis_data:
  dronesim_logs:
