# syntax=docker/dockerfile:1
version: '3.8'

services:
  #nginx:
  #  image: nginx:latest
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./config/nginx:/etc/nginx/conf.d
  #   - static_volume:/code/static
  #  depends_on:
  #     - web

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn dronesim.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db

volumes:
  postgres_data:
