FROM python:3

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y netcat-traditional

# Install python dependencies
RUN pip install --upgrade pip
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.dev.sh .
RUN sed -i 's/\r$//g' /app/entrypoint.dev.sh
RUN chmod +x /app/entrypoint.dev.sh

# Copy project
COPY . /app/

# Collect static files
#RUN python manage.py collectstatic --noinput

ENTRYPOINT ["/app/entrypoint.dev.sh"]
